repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Format Rust code with cargo fmt
        entry: cargo fmt --
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        description: Run Clippy lints with cargo clippy
        entry: cargo clippy --all-targets --all-features -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false
